version: '3'
services:

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        hostname: mysql
        ports: 
            - "3306"
        restart: unless-stopped
        volumes: 
            - db_data:/var/lib/mysql
            - ./mysqldata:/var/lib/mysql:rw,delegated
            # - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
        environment: 
            MYSQL_ROOT_PASSWORD: bluetide
            MYSQL_DATABASE: bluetide
            MYSQL_USER: bluetide
            MYSQL_PASSWORD: bluetide
    ## Database MYSQL
    db:
        image: postgres:latest

    ## Wordpress First APP
    wordpress:
        image: wordpress:latest
        container_name: wordpress_container
        restart: unless-stopped
        ports: 
            - 5000:80
        depends_on: 
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: bluetide
            WORDPRESS_DB_NAME: bluetide
            WORDPRESS_DB_PASSWORD: bluetide
        volumes: 
            - ./wordpress-data:/var/www/html/
    ## Django Image setup
    django:
        build: './images/django'
        container_name: django_container
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./django:/espaciocivico_guia
        ports: 
            - 8000:8000
        expose:
            - "8000"
        depends_on: 
            - db
volumes:
    db_data:
    wordpress-data: